aliases = {
    "AzurLane": "Azur Lane",
    "BanG Dream!": "BanG Dream",
    "BlueArchive": "Blue Archive",
    "Ceres Fauna": "Hololive",
    "DrawMillie": "Nijisanji",
    "FGO": "Fate Grand Order",
    "FUWAMOCO": "Hololive",
    "Fate/GO": "Fate Grand Order",
    "Fate/Grand Order": "Fate Grand Order",
    "Fate/GrandOrder": "Fate Grand Order",
    "Gakuen IDOLM@STER": "The Idolmaster",
    "GenshinImpact": "Genshin Impact",
    "Guilty Gear -Strive-": "Guilty Gear",
    "Hololive EN": "Hololive",
    "HololiveEN": "Hololive",
    "InART": "Hololive",
    "Is It Wrong to Try to Pick Up Girls in a Dungeon?": "DanMachi",
    "KanColle": "Kantai Collection",
    "Kancolle": "Kantai Collection",
    "LycorisRecoil": "Lycoris Recoil",
    "MadeinAbyss": "Made in Abyss",
    "Marisa Kirisame": "Touhou Project",
    "Miss Kobayashi's Dragon Maid S": "Miss Kobayashi's Dragon Maid",
    "NIKKE": "NIKKE: The Goddess of Victory",
    "ONEPIECE": "One Piece",
    "Original": "original",
    "Pekora": "Hololive",
    "ReGLOSS": "Hololive",
    "The Idolmaster: Cinderella Girls": "The Idolmaster",
    "The Idolmaster: Million Live!": "The Idolmaster",
    "The Idolmaster: Shiny Colors": "The Idolmaster",
    "Touhou": "Touhou Project",
    "Vtuber": "VTuber",
    "Xenoblade 3": "Xenoblade",
    "ace attorney": "Ace Attorney",
    "bleach": "Bleach",
    "charlotte dunois": "Infinite Stratos",
    "eva": "Neon Genesis Evangelion",
    "evangelion": "Neon Genesis Evangelion",
    "fire emblem": "Fire Emblem",
    "genshinimpact": "Genshin Impact",
    "hatsune miku": "Hatsune Miku",
    "high school girl": "girl",
    "hololive": "Hololive",
    "human characters in Pokémon": "Pokémon",
    "imas": "The Idolmaster",
    "kill la kill": "Kill la Kill",
    "monogatari series": "Monogatari series",
    "neon genesis evangelion": "Neon Genesis Evangelion",
    "office lady": "OL",
    "original character": "original",
    "original works": "original",
    "rei ayanami": "Neon Genesis Evangelion",
    "rozen maiden": "Rozen Maiden",
    "senki zesshou symphogear": "Symphogear",
    "soul eater": "Soul Eater",
    "the legend of zelda": "The Legend of Zelda",
    "the powerpuff girls": "The Powerpuff Girls",
    "virtual YouTuber": "VTuber",
    "vocaloid": "VOCALOID",
    "xenoblade": "Xenoblade",
    "young girl": "girl",
    "zzzero": "Zenless Zone Zero",
    "ぼっち・ざ・ろっく!": "Bocchi the Rock",
    "ブルアカ": "Blue Archive",
    "推しの子": "Oshi no Ko",
}

categories = [
    "Ace Attorney",
    "Akiba Maid War",
    "Arknights",
    "Azur Lane",
    "BanG Dream",
    "Bleach",
    "Blue Archive",
    "Bocchi the Rock",
    "Call of the Night",
    "Cardcaptor Sakura",
    "Chainsaw Man",
    "Command & Conquer",
    "Cyberpunk: Edgerunners",
    "DanMachi",
    "Dandadan",
    "Darkstalkers",
    "Delicious in Dungeon",
    "Elden Ring",
    "FF14",
    "Fate Grand Order",
    "Fire Emblem",
    "Frieren at the Funeral",
    "GATE",
    "Genshin Impact",
    "Girls und Panzer",
    "Girls' Frontline",
    "Golden Kamuy",
    "Granblue Fantasy",
    "Guilty Gear",
    "Hatsune Miku",
    "Helltaker",
    "Hololive",
    "Honkai Impact 3",
    "Honkai: Star Rail",
    "Infinite Stratos",
    "Kantai Collection",
    "Kill la Kill",
    "Komi Can't Communicate",
    "KonoSuba",
    "Land of the Lustrous",
    "Looking Up To Magical Girls",
    "Lucky Star",
    "Lycoris Recoil",
    "Made in Abyss",
    "Miss Kobayashi's Dragon Maid",
    "Mobile Suit Gundam: The Witch From Mercury",
    "Monogatari series",
    "Mushoku Tensei",
    "My Dress-Up Darling",
    "NEEDY_GIRL_OVERDOSE",
    "NIKKE: The Goddess of Victory",
    "Neon Genesis Evangelion",
    "Nijisanji",
    "OL",
    "One Piece",
    "Onimai: I'm Now Your Sister!",
    "Oshi no Ko",
    "Pokémon",
    "Princess Connect! Re:Dive",
    "Puella Magi Madoka Magica",
    "RWBY",
    "Re:Zero",
    "Rent-A-Girlfriend",
    "Rozen Maiden",
    "SPY×FAMILY",
    "SSSS.Gridman",
    "Shadowverse",
    "Soul Eater",
    "Symphogear",
    "Takt Op.",
    "The Idolmaster",
    "The Legend of Zelda",
    "The Powerpuff Girls",
    "The Wandering Earth",
    "Touhou Project",
    "Uma Musume Pretty Derby",
    "VOCALOID",
    "VTuber",
    "Wuthering Waves",
    "Xenoblade",
    "Yu-Gi-Oh!",
    "Zenless Zone Zero",
    "bunny girl",
    "creation",
    "furry",
    "girl",
    "maid",
    "original",
    "transforming into female",
]
