aliases = {
    "AzurLane": "Azur Lane",
    "BlueArchive": "Blue Archive",
    "FGO": "Fate Grand Order",
    "Fate/GO": "Fate Grand Order",
    "Fate/GrandOrder": "Fate Grand Order",
    "Gakuen IDOLM@STER": "The Idolmaster",
    "GenshinImpact": "Genshin Impact",
    "Hololive EN": "Hololive",
    "KanColle": "Kantai Collection",
    "LycorisRecoil": "Lycoris Recoil",
    "Marisa Kirisame": "Touhou Project",
    "NIKKE": "NIKKE: The Goddess of Victory",
    "Original": "original",
    "ReGLOSS": "Hololive",
    "The Idolmaster: Million Live!": "The Idolmaster",
    "The Idolmaster: Shiny Colors": "The Idolmaster",
    "Touhou": "Touhou Project",
    "hatsune miku": "Hatsune Miku",
    "high school girl": "girl",
    "hololive": "Hololive",
    "imas": "The Idolmaster",
    "original character": "original",
    "rozen maiden": "Rozen Maiden",
    "xenoblade": "Xenoblade",
    "young girl": "girl",
    "zzzero": "Zenless Zone Zero",
    "ブルアカ": "Blue Archive",
}

categories = [
    "Akiba Maid War",
    "Arknights",
    "Azur Lane",
    "Blue Archive",
    "Bocchi the Rock!",
    "Command & Conquer",
    "Dandadan",
    "Delicious in Dungeon",
    "Fate Grand Order",
    "Frieren at the Funeral",
    "Genshin Impact",
    "Girls' Frontline",
    "Guilty Gear",
    "Hatsune Miku",
    "Hololive",
    "Honkai Impact 3",
    "Honkai: Star Rail",
    "Kantai Collection",
    "Komi Can't Communicate",
    "Lycoris Recoil",
    "NIKKE: The Goddess of Victory",
    "Onimai: I'm Now Your Sister!",
    "Rozen Maiden",
    "Takt Op.",
    "The Idolmaster",
    "Touhou Project",
    "Xenoblade",
    "Zenless Zone Zero",
    "original",
]
