aliases = {
    "AzurLane": "Azur Lane",
    "BlueArchive": "Blue Archive",
    "Ceres Fauna": "Hololive",
    "FGO": "Fate Grand Order",
    "Fate/GO": "Fate Grand Order",
    "Fate/Grand Order": "Fate Grand Order",
    "Fate/GrandOrder": "Fate Grand Order",
    "Gakuen IDOLM@STER": "The Idolmaster",
    "GenshinImpact": "Genshin Impact",
    "Hololive EN": "Hololive",
    "KanColle": "Kantai Collection",
    "Kancolle": "Kantai Collection",
    "LycorisRecoil": "Lycoris Recoil",
    "Marisa Kirisame": "Touhou Project",
    "NIKKE": "NIKKE: The Goddess of Victory",
    "Original": "original",
    "ReGLOSS": "Hololive",
    "The Idolmaster: Million Live!": "The Idolmaster",
    "The Idolmaster: Shiny Colors": "The Idolmaster",
    "Touhou": "Touhou Project",
    "eva": "Neon Genesis Evangelion",
    "evangelion": "Neon Genesis Evangelion",
    "hatsune miku": "Hatsune Miku",
    "high school girl": "girl",
    "hololive": "Hololive",
    "imas": "The Idolmaster",
    "original character": "original",
    "original works": "original",
    "rei ayanami": "Neon Genesis Evangelion",
    "rozen maiden": "Rozen Maiden",
    "soul eater": "Soul Eater",
    "xenoblade": "Xenoblade",
    "young girl": "girl",
    "zzzero": "Zenless Zone Zero",
    "ぼっち・ざ・ろっく!": "Bocchi the Rock",
    "ブルアカ": "Blue Archive",
    "推しの子": "Oshi no Ko",
}

categories = [
    "Akiba Maid War",
    "Arknights",
    "Azur Lane",
    "Blue Archive",
    "Bocchi the Rock",
    "Call of the Night",
    "Chainsaw Man",
    "Command & Conquer",
    "Cyberpunk: Edgerunners",
    "Dandadan",
    "Delicious in Dungeon",
    "FF14",
    "Fate Grand Order",
    "Frieren at the Funeral",
    "GATE",
    "Genshin Impact",
    "Girls und Panzer",
    "Girls' Frontline",
    "Golden Kamuy",
    "Granblue Fantasy",
    "Guilty Gear",
    "Hatsune Miku",
    "Hololive",
    "Honkai Impact 3",
    "Honkai: Star Rail",
    "Kantai Collection",
    "Komi Can't Communicate",
    "Looking Up To Magical Girls",
    "Lucky Star",
    "Lycoris Recoil",
    "Mushoku Tensei",
    "NIKKE: The Goddess of Victory",
    "Neon Genesis Evangelion",
    "Nijisanji",
    "Onimai: I'm Now Your Sister!",
    "Oshi no Ko",
    "Princess Connect! Re:Dive",
    "Re:Zero",
    "Rozen Maiden",
    "Soul Eater",
    "Takt Op.",
    "The Idolmaster",
    "Touhou Project",
    "VOCALOID",
    "Xenoblade",
    "Zenless Zone Zero",
    "original",
]
